/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazong;

import componentead.Rol;
import imagenes.LogicaNegocio;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class NuevoRol extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form NuevoRol
     */
    public NuevoRol() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Nuevo rol");
        menu = new JMenuBar();
        this.setJMenuBar(menu);
        opcion1 = new JMenu("Opciones");
        menu.add(opcion1);
        elemento1 = new JMenuItem("Perfil");
        elemento1.addActionListener(this);
        opcion1.add(elemento1);
        elemento2 = new JMenuItem("Contacto");
        elemento2.addActionListener(this);
        opcion1.add(elemento2);
        elemento4 = new JMenuItem("Usuarios");
        elemento4.addActionListener(this);
        opcion1.add(elemento4);
        elemento5 = new JMenuItem("Roles");
        elemento5.addActionListener(this);
        opcion1.add(elemento5);
        elemento6 = new JMenuItem("Permisos");
        elemento6.addActionListener(this);
        opcion1.add(elemento6);
        elemento7 = new JMenuItem("Productos");
        elemento7.addActionListener(this);
        opcion1.add(elemento7);
        elemento8 = new JMenuItem("Colaboradores");
        elemento8.addActionListener(this);
        opcion1.add(elemento8);
        elemento9 = new JMenuItem("Categorias");
        elemento9.addActionListener(this);
        opcion1.add(elemento9);
        elemento3 = new JMenuItem("Salir");
        elemento3.addActionListener(this);
        opcion1.add(elemento3);
        etiqueta1.setText("Nombre Rol: ");
        caja1.setText("");
        etiqueta2.setText("Descripción: ");
        area1.setText("");
        boton1.setText("Crear Rol");
        boton2.setText("Cancelar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JPanel();
        etiqueta1 = new javax.swing.JLabel();
        etiqueta2 = new javax.swing.JLabel();
        caja1 = new javax.swing.JTextField();
        panel1 = new javax.swing.JScrollPane();
        area1 = new javax.swing.JTextArea();
        boton1 = new javax.swing.JButton();
        boton2 = new javax.swing.JButton();
        menu = new javax.swing.JMenuBar();
        opcion1 = new javax.swing.JMenu();
        elemento1 = new javax.swing.JMenuItem();
        elemento2 = new javax.swing.JMenuItem();
        elemento4 = new javax.swing.JMenuItem();
        elemento5 = new javax.swing.JMenuItem();
        elemento6 = new javax.swing.JMenuItem();
        elemento7 = new javax.swing.JMenuItem();
        elemento8 = new javax.swing.JMenuItem();
        elemento9 = new javax.swing.JMenuItem();
        elemento3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etiqueta1.setText("jLabel1");

        etiqueta2.setText("jLabel1");

        caja1.setText("jTextField1");

        area1.setColumns(20);
        area1.setRows(5);
        panel1.setViewportView(area1);

        boton1.setText("jButton1");
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });

        boton2.setText("jButton1");
        boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiqueta1)
                    .addComponent(etiqueta2))
                .addGap(54, 54, 54)
                .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caja1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(contenedorLayout.createSequentialGroup()
                        .addComponent(boton1)
                        .addGap(18, 18, 18)
                        .addComponent(boton2)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqueta1)
                    .addComponent(caja1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiqueta2)
                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton1)
                    .addComponent(boton2))
                .addGap(53, 53, 53))
        );

        opcion1.setText("File");

        elemento1.setText("jMenuItem1");
        opcion1.add(elemento1);

        elemento2.setText("jMenuItem1");
        opcion1.add(elemento2);

        elemento4.setText("jMenuItem1");
        opcion1.add(elemento4);

        elemento5.setText("jMenuItem1");
        opcion1.add(elemento5);

        elemento6.setText("jMenuItem1");
        opcion1.add(elemento6);

        elemento7.setText("jMenuItem1");
        opcion1.add(elemento7);

        elemento8.setText("jMenuItem1");
        opcion1.add(elemento8);

        elemento9.setText("jMenuItem1");
        opcion1.add(elemento9);

        elemento3.setText("jMenuItem1");
        opcion1.add(elemento3);

        menu.add(opcion1);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
        // TODO add your handling code here:
        String nombre = caja1.getText();
        String descripcion = area1.getText();
        Rol rol = new Rol(nombre,descripcion);
        if (validarDatos()) {
            if (rol.getNombre().length() <= 50) {
                if (rol.getDescripcion().length() <= 100) {
                    Roles roles = new Roles();
                    roles.setVisible(true);
                    LogicaNegocio.añadirRol(rol);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Error", "La descripcion del rol debe tener una longitud maxima de 100 caracteres", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Error", "El nombre del rol debe tener una longitud maxima de 50 caracteres", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_boton1ActionPerformed

    private void boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton2ActionPerformed
        // TODO add your handling code here:
        Roles roles = new Roles();
        roles.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoRol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoRol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoRol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoRol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoRol().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area1;
    private javax.swing.JButton boton1;
    private javax.swing.JButton boton2;
    private javax.swing.JTextField caja1;
    private javax.swing.JPanel contenedor;
    private javax.swing.JMenuItem elemento1;
    private javax.swing.JMenuItem elemento2;
    private javax.swing.JMenuItem elemento3;
    private javax.swing.JMenuItem elemento4;
    private javax.swing.JMenuItem elemento5;
    private javax.swing.JMenuItem elemento6;
    private javax.swing.JMenuItem elemento7;
    private javax.swing.JMenuItem elemento8;
    private javax.swing.JMenuItem elemento9;
    private javax.swing.JLabel etiqueta1;
    private javax.swing.JLabel etiqueta2;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu opcion1;
    private javax.swing.JScrollPane panel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        Perfil perfil = new Perfil();
        Contacto contacto = new Contacto();
        Roles roles = new Roles();
        Permisos permisos = new Permisos();
        Productos productos = new Productos();
        Colaboradores colaboradores = new Colaboradores();
        Categorias categorias = new Categorias();
        Login login = new Login();

        if (e.getSource() == elemento1) {
            perfil.setVisible(true);
            this.dispose();
        }
        if (e.getSource() == elemento2) {
            contacto.setVisible(true);
            this.dispose();
        }
        if (e.getSource() == elemento5) {
            roles.setVisible(true);
            this.dispose();
        }
        if (e.getSource() == elemento6) {
            permisos.setVisible(true);
            this.dispose();
        }
        if (e.getSource() == elemento7) {
            productos.setVisible(true);
            this.dispose();
        }
        if (e.getSource() == elemento8) {
            colaboradores.setVisible(true);
            this.dispose();
        }
        if (e.getSource() == elemento9) {
            categorias.setVisible(true);
            this.dispose();
        }
        if (e.getSource() == elemento3) {
            login.setVisible(true);
            this.dispose();
        }
    }

    private boolean validarDatos() {
        String caracterNumerico = "0123456789";
        String msgError = "El nombre del rol no debe empezar por un numero";
        String msgWarning = "Toda la información del rol es obligatorio";
        if (caja1.getText().startsWith(caracterNumerico) && area1.getText().startsWith(caracterNumerico)) {
            JOptionPane.showMessageDialog(this, "Error", msgError, JOptionPane.ERROR_MESSAGE);
            return false;
        } else {
            if (!caja1.getText().isEmpty() && !area1.getText().isEmpty()) {
                return true;
            } else {
                JOptionPane.showMessageDialog(this, "Aviso", msgWarning, JOptionPane.WARNING_MESSAGE);
                return false;
            }
        }
    }
}
