/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazong;

import componentead.Usuario;
import imagenes.LogicaNegocio;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Registrarse extends javax.swing.JFrame {

    /**
     * Creates new form Registrar
     */
    public Registrarse() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Registrarse");
        etiqueta1.setText("Nombre: ");
        caja1.setText("");
        etiqueta2.setText("Email: ");
        caja2.setText("");
        etiqueta3.setText("Contraseña: ");
        caja3.setText("");
        etiqueta4.setText("Confirmar contraseña: ");
        caja4.setText("");
        etiqueta5.setText("Imagen: ");
        boton1.setText("Seleccionar imagen");
        etiqueta6.setText("");
        boton2.setText("Registrar");
        boton3.setText("Cancelar");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        contenedor = new javax.swing.JPanel();
        etiqueta1 = new javax.swing.JLabel();
        caja1 = new javax.swing.JTextField();
        etiqueta2 = new javax.swing.JLabel();
        caja2 = new javax.swing.JTextField();
        etiqueta3 = new javax.swing.JLabel();
        caja3 = new javax.swing.JPasswordField();
        etiqueta4 = new javax.swing.JLabel();
        caja4 = new javax.swing.JPasswordField();
        etiqueta5 = new javax.swing.JLabel();
        boton1 = new javax.swing.JButton();
        etiqueta6 = new javax.swing.JLabel();
        boton2 = new javax.swing.JButton();
        boton3 = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        jLabel5.setText("jLabel5");

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etiqueta1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etiqueta1.setText("jLabel1");

        caja1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        caja1.setText("jTextField1");

        etiqueta2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etiqueta2.setText("jLabel3");

        caja2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        caja2.setText("jTextField2");

        etiqueta3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etiqueta3.setText("jLabel4");

        caja3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        caja3.setText("jPasswordField1");

        etiqueta4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etiqueta4.setText("jLabel6");

        caja4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        caja4.setText("jPasswordField2");

        etiqueta5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etiqueta5.setText("jLabel7");

        boton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        boton1.setText("jButton1");
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });

        etiqueta6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etiqueta6.setText("jLabel9");

        boton2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        boton2.setText("jButton2");
        boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton2ActionPerformed(evt);
            }
        });

        boton3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        boton3.setText("jButton3");
        boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorLayout.createSequentialGroup()
                .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenedorLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(boton2)
                        .addGap(18, 18, 18)
                        .addComponent(boton3))
                    .addGroup(contenedorLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(etiqueta2)
                            .addComponent(etiqueta1)
                            .addComponent(etiqueta3)
                            .addComponent(etiqueta4)
                            .addComponent(etiqueta5))
                        .addGap(83, 83, 83)
                        .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(etiqueta6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(caja1)
                            .addComponent(caja2)
                            .addComponent(caja3, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(caja4)
                            .addComponent(boton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqueta1)
                    .addComponent(caja1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqueta2)
                    .addComponent(caja2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqueta3)
                    .addComponent(caja3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqueta4)
                    .addComponent(caja4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqueta5)
                    .addComponent(boton1))
                .addGap(18, 18, 18)
                .addComponent(etiqueta6)
                .addGap(37, 37, 37)
                .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton3)
                    .addComponent(boton2))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser imagen = new JFileChooser();
        imagen.showOpenDialog(this);
        File fichero = imagen.getSelectedFile();
        if (fichero != null) {
            String ruta = fichero.getPath();
            //ImageIcon imageIcon = new ImageIcon(ruta);
            this.etiqueta6.setText(ruta);
        } else {
            JOptionPane.showMessageDialog(null, "Por favor seleccione un archivo");
        }

    }//GEN-LAST:event_boton1ActionPerformed

    private void boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton2ActionPerformed
        // TODO add your handling code here:
        String username = caja1.getText();
        String email = caja2.getText();
        String password = caja3.getSelectedText();
        String confirmarPassword = caja4.getSelectedText();
        String picture = etiqueta6.getText();
        if (validarDatos()) {
            Menu menu = new Menu();
            menu.setVisible(true);
            Usuario usuario = new Usuario(username,email, password, picture);
            LogicaNegocio.añadirUsuario(usuario); 
            this.dispose();
        }
    }//GEN-LAST:event_boton2ActionPerformed

    private void boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton3ActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrarse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton1;
    private javax.swing.JButton boton2;
    private javax.swing.JButton boton3;
    private javax.swing.JTextField caja1;
    private javax.swing.JTextField caja2;
    private javax.swing.JPasswordField caja3;
    private javax.swing.JPasswordField caja4;
    private javax.swing.JPanel contenedor;
    private javax.swing.JLabel etiqueta1;
    private javax.swing.JLabel etiqueta2;
    private javax.swing.JLabel etiqueta3;
    private javax.swing.JLabel etiqueta4;
    private javax.swing.JLabel etiqueta5;
    private javax.swing.JLabel etiqueta6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables

    private boolean validarDatos() {
        String caracterNumerico = "0123456789";
        String msgError = "El nombre del usuario no debe empezar por un numero";
        String msgWarning = "El nomnbre es obligatorio";
        if (caja1.getText().startsWith(caracterNumerico)) {
            JOptionPane.showMessageDialog(this, "Error", msgError, JOptionPane.ERROR_MESSAGE);
            return false;
        } else {
            if (!(caja1.getText().isEmpty() && caja2.getText().isEmpty() && caja3.getSelectedText().isEmpty()
                    && caja4.getSelectedText().isEmpty())) {
                return true;
            } else {
                JOptionPane.showMessageDialog(this, "Aviso", msgWarning, JOptionPane.WARNING_MESSAGE);
                return false;
            }
        }

    }
}
